version: 2

# Define the jobs we want to run for this project
jobs:
  test:
    docker:
      - image: circleci/python:3.7.3
    steps:
      - checkout
      - run: sudo pip install -r requirements.txt
      - run: python -m unittest

# Orchestrate our job run sequence
workflows:
  version: 2
  build_and_test:
    jobs:
      - test